// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7jl41uWEo_FQBVu7eR5NgKUvX5Mo3_E',
    appId: '1:447142741538:web:82c2d472ef3d3ce5c86c7b',
    messagingSenderId: '447142741538',
    projectId: 'actividad3flutter',
    authDomain: 'actividad3flutter.firebaseapp.com',
    storageBucket: 'actividad3flutter.firebasestorage.app',
    measurementId: 'G-EHRZK4HRSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJyP2qmfu_EPKhZxAMjG8_jVWaVPIdlB8',
    appId: '1:447142741538:android:29a8a7ca4ee0b47cc86c7b',
    messagingSenderId: '447142741538',
    projectId: 'actividad3flutter',
    storageBucket: 'actividad3flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1ixCeBVYUhZxKqyVO0LiT2MXluCp8Zg',
    appId: '1:447142741538:ios:edf899e856d88c91c86c7b',
    messagingSenderId: '447142741538',
    projectId: 'actividad3flutter',
    storageBucket: 'actividad3flutter.firebasestorage.app',
    iosBundleId: 'com.example.actividad3App',
  );

}